# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Fri Aug 16 15:51:46 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(920, 800)
        MainWindow.setMinimumSize(QtCore.QSize(920, 800))
        MainWindow.setMaximumSize(QtCore.QSize(920, 800))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8("XYZLRAconverter"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Icons/app_icon1.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 721))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        # self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.XYZtable = QtWidgets.QTableWidget(self.layoutWidget)
        self.XYZtable.setEnabled(True)
        self.XYZtable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.XYZtable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.XYZtable.setObjectName(_fromUtf8("XYZtable"))
        self.XYZtable.setColumnCount(3)
        self.XYZtable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.XYZtable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.XYZtable.setHorizontalHeaderItem(2, item)
        self.XYZtable.horizontalHeader().setCascadingSectionResizes(False)
        self.XYZtable.horizontalHeader().setDefaultSectionSize(160)
        self.XYZtable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.XYZtable)
        self.LRAtable = QtWidgets.QTableWidget(self.layoutWidget)
        self.LRAtable.setAlternatingRowColors(True)
        self.LRAtable.setObjectName(_fromUtf8("LRAtable"))
        self.LRAtable.setColumnCount(3)
        self.LRAtable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.LRAtable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LRAtable.setHorizontalHeaderItem(2, item)
        self.LRAtable.horizontalHeader().setCascadingSectionResizes(False)
        self.LRAtable.horizontalHeader().setDefaultSectionSize(160)
        self.LRAtable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.LRAtable)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(570, 20, 330, 250))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LineEditOuterDia = QtWidgets.QLineEdit(self.groupBox)
        self.LineEditOuterDia.setObjectName(_fromUtf8("LineEditOuterDia"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEditOuterDia)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LineEditWallThickness = QtWidgets.QLineEdit(self.groupBox)
        self.LineEditWallThickness.setObjectName(_fromUtf8("LineEditWallThickness"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEditWallThickness)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LineEditCLR = QtWidgets.QLineEdit(self.groupBox)
        self.LineEditCLR.setObjectName(_fromUtf8("LineEditCLR"))
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEditCLR)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.LineEditLength = QtWidgets.QLineEdit(self.groupBox)
        self.LineEditLength.setEnabled(False)
        self.LineEditLength.setObjectName(_fromUtf8("LineEditLength"))
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEditLength)
        self.horizontalLayout.addLayout(self.formLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.RadioLRA2XYZ = QtWidgets.QRadioButton(self.groupBox_2)
        self.RadioLRA2XYZ.setObjectName(_fromUtf8("RadioLRA2XYZ"))
        self.verticalLayout_2.addWidget(self.RadioLRA2XYZ)
        self.RadioXYZ2LRA = QtWidgets.QRadioButton(self.groupBox_2)
        self.RadioXYZ2LRA.setObjectName(_fromUtf8("RadioXYZ2LRA"))
        self.verticalLayout_2.addWidget(self.RadioXYZ2LRA)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ConvertButton = QtWidgets.QPushButton(self.groupBox_2)
        self.ConvertButton.setMinimumSize(QtCore.QSize(100, 40))
        self.ConvertButton.setObjectName(_fromUtf8("ConvertButton"))
        self.horizontalLayout_2.addWidget(self.ConvertButton)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 360, 330, 381))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditProjectNo = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditProjectNo.setObjectName(_fromUtf8("lineEditProjectNo"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditProjectNo)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEditRev = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditRev.setObjectName(_fromUtf8("lineEditRev"))
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditRev)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.textEditNotes = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEditNotes.setObjectName(_fromUtf8("textEditNotes"))
        self.verticalLayout_3.addWidget(self.textEditNotes)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName(_fromUtf8("actionImport_Data"))
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExport_Data = QtWidgets.QAction(MainWindow)
        self.actionExport_Data.setObjectName(_fromUtf8("actionExport_Data"))
        self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Report.setObjectName(_fromUtf8("actionGenerate_Report"))
        self.actionGenerate_Report_2 = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Report_2.setObjectName(_fromUtf8("actionGenerate_Report_2"))
        self.menuSave.addAction(self.actionNew)
        self.menuSave.addAction(self.actionImport_Data)
        self.menuSave.addAction(self.actionExport_Data)
        self.menuTools.addAction(self.actionGenerate_Report_2)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.XYZtable, self.LRAtable)
        MainWindow.setTabOrder(self.LRAtable, self.LineEditOuterDia)
        MainWindow.setTabOrder(self.LineEditOuterDia, self.LineEditWallThickness)
        MainWindow.setTabOrder(self.LineEditWallThickness, self.LineEditCLR)
        MainWindow.setTabOrder(self.LineEditCLR, self.LineEditLength)
        MainWindow.setTabOrder(self.LineEditLength, self.RadioLRA2XYZ)
        MainWindow.setTabOrder(self.RadioLRA2XYZ, self.RadioXYZ2LRA)
        MainWindow.setTabOrder(self.RadioXYZ2LRA, self.ConvertButton)

    def retranslateUi(self, MainWindow):
        item = self.XYZtable.verticalHeaderItem(0)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "1"))
        item = self.XYZtable.horizontalHeaderItem(0)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "X"))
        item = self.XYZtable.horizontalHeaderItem(1)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "Y"))
        item = self.XYZtable.horizontalHeaderItem(2)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "Z"))
        item = self.LRAtable.verticalHeaderItem(0)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "1"))
        item = self.LRAtable.horizontalHeaderItem(0)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "Length"))
        item = self.LRAtable.horizontalHeaderItem(1)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "Rotation"))
        item = self.LRAtable.horizontalHeaderItem(2)
        item.setText(QtWidgets.QApplication.translate("MainWindow", "Angle"))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tube \\ Pipe data"))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Outer diameter"))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Wall thickness"))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "CLR"))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Length"))
        self.RadioLRA2XYZ.setText(QtWidgets.QApplication.translate("MainWindow", "LRA to XYZ"))
        self.RadioXYZ2LRA.setText(QtWidgets.QApplication.translate("MainWindow", "XYZ to LRA"))
        self.ConvertButton.setText(QtWidgets.QApplication.translate("MainWindow", "Convert"))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Project Information"))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Project number"))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Revision"))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Notes"))
        self.menuSave.setTitle(QtWidgets.QApplication.translate("MainWindow", "File"))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools"))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save"))
        self.actionSave_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save As ..."))
        self.actionImport_Data.setText(QtWidgets.QApplication.translate("MainWindow", "Import Data"))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Open"))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New"))
        self.actionExport_Data.setText(QtWidgets.QApplication.translate("MainWindow", "Export Data"))
        self.actionGenerate_Report.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Report"))
        self.actionGenerate_Report_2.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Report"))

